spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/cadastro_chave_pix?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/cadastro_chave_pix?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    user: root
    password: root